---
stages:
  - dependencies
  - build
  - test
  - checks
  - publish

variables:
  SCCACHE_GCS_BUCKET: btm-build-cache
  SCCACHE_GCS_RW_MODE: READ_WRITE
  SCCACHE_GCS_KEY_PATH: /tmp/storage-key.json
  DOCKER_DRIVER: overlay2
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

before_script:
  - exit 1
  - echo $GCS_STORAGE_KEY > $SCCACHE_GCS_KEY_PATH

create builder:
  stage: dependencies
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
  allow_failure: true
  image: docker:stable
  only:
    refs:
      - master
  services:
    - docker:dind
  before_script:
    - set -- $CI_JOB_NAME
    - export DOCKER_HOST="${DOCKER_HOST:-tcp://localhost:2375/}"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/builder:latest || true
    - docker pull rustlang/rust:nightly || true
  script:
    - >
      docker build -f Dockerfile.builder
      --cache-from $CI_REGISTRY_IMAGE/builder:latest
      --cache-from rustlang/rust:nightly
      --tag $CI_REGISTRY_IMAGE/builder:latest
      .
    - docker push $CI_REGISTRY_IMAGE/builder:latest

.build_script: &build_script
  stage: build
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
  image: $CI_REGISTRY_IMAGE/builder:latest
  script:
    - set -- $CI_JOB_NAME
    - export TARGET=$1
    - echo Running build for TARGET=$TARGET
    - cargo build --verbose --all
  artifacts:
    paths:
      - target/
    expire_in: 30 days
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cargo/registry

i686-apple-darwin build: *build_script
i686-pc-windows-gnu build: *build_script
i686-pc-windows-msvc build: *build_script
i686-unknown-linux-gnu build: *build_script
x86_64-apple-darwin build: *build_script
x86_64-pc-windows-gnu build: *build_script
x86_64-pc-windows-msvc build: *build_script
x86_64-unknown-freebsd build: *build_script
x86_64-unknown-linux-gnu build: *build_script

.test_script: &test_script
  stage: test
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
  image: $CI_REGISTRY_IMAGE/builder:latest
  script:
    - set -- $CI_JOB_NAME
    - export TARGET=$1
    - cargo test --verbose --all --target $TARGET
    - |
      if [[ "$TARGET" == "x86_64-unknown-linux-gnu" ]]; then
        cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash)
      fi
  coverage: '/(\d+.\d+%) coverage,/'
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cargo/registry

x86_64-unknown-linux-gnu test:
  <<: *test_script
  dependencies:
    - x86_64-unknown-linux-gnu build

clippy:
  stage: checks
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
  image: $CI_REGISTRY_IMAGE/builder:latest
  script:
    - cargo clippy --all-targets --all-features -- -D warnings
  dependencies:
    - x86_64-unknown-linux-gnu build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cargo/registry

rustfmt:
  stage: checks
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
  image: $CI_REGISTRY_IMAGE/builder:latest
  script:
    - cargo fmt --all -- --check
  dependencies:
    - x86_64-unknown-linux-gnu build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cargo/registry

cargo publish:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
  only:
    - tags
  variables:
    CARGO_HOME: /usr/local/cargo
  stage: publish
  image: $CI_REGISTRY_IMAGE/builder:latest
  script:
    - cargo publish --token $CRATESIO_TOKEN
  dependencies:
    - x86_64-unknown-linux-gnu build

.github_deploy: &github_deploy
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
  only:
    - tags
  stage: publish
  image: $CI_REGISTRY_IMAGE/builder:latest
  script:
    - set -- $CI_JOB_NAME
    - export TARGET=$1
    - cargo build --release
    - RELEASE_NAME="labhub-$CI_COMMIT_TAG-$TARGET"
    - mkdir $RELEASE_NAME
    - cp target/release/labhub $RELEASE_NAME/
    - cp README.md LICENSE $RELEASE_NAME/
    - tar czvf $RELEASE_NAME.tar.gz $RELEASE_NAME
    - echo -n $(shasum -ba 256 "$RELEASE_NAME.tar.gz" | cut -d " " -f 1) > $RELEASE_NAME.tar.gz.sha256
    - github-release release -u brndnmtthws -r labhub -t $CI_COMMIT_TAG --name "LabHub $CI_COMMIT_TAG"
    - github-release upload -u brndnmtthws -r labhub -t $CI_COMMIT_TAG --name $RELEASE_NAME.tar.gz -f $RELEASE_NAME.tar.gz
    - github-release upload -u brndnmtthws -r labhub -t $CI_COMMIT_TAG --name $RELEASE_NAME.tar.gz.sha256 -f $RELEASE_NAME.tar.gz.sha256
  dependencies:
    - x86_64-unknown-linux-gnu build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cargo/registry

x86_64-unknown-linux-gnu publish: *github_deploy
