# List of enabled features
features = [
    "external_pr",
    "commands"
]

# Command settings
[commands]
# List of commands to enable
enabled_commands = [
    "retry",
]

# Settings for GitHub
[github]
webhook_secret = "secret"
username = "ci-user"
ssh_key = "/etc/ssh-keys/labhub-key.ecdsa"
api_token = "token"
hostname = "github.com"

# Settings for GitLab
[gitlab]
webhook_secret = "secret"
username = "ci-user"
ssh_key = "/etc/ssh-keys/labhub-key.ecdsa"
api_token = "token"
hostname = "gitlab.com"

# List of mappings to/from GitHub & GitLab
[[mappings]]
github_repo = "brndnmtthws/labhub"
gitlab_repo = "brndnmtthws-oss/labhub"
[[mappings]]
github_repo = "brndnmtthws/conky"
gitlab_repo = "brndnmtthws-oss/conky"

# pull request event trigger actions
[actions]
# list of enabled actions
enabled_actions = [
    "assigned",
    "closed",
    "edited",
    "labeled",
    "locked",
    "opened",
    "ready_for_review",
    "reopened",
    "review_requested",
    "review_request_removed",
    "synchronize",
    "unassigned",
    "unlabeled",
    "unlocked",
]
